[workspace]
authors = ["Riccardo Cappuzzo <riccardo.cappuzzo@gmail.com>"]
channels = ["conda-forge"]
name = "skrub-materials"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
skrub = ">=0.6.2,<0.7"
ipython = ">=9.7.0,<10"
jupyter = ">=1.1.1,<2"
polars = ">=1.35.1,<2"
pyarrow = ">=22.0.0,<23"
plotly = ">=6.5.0,<7"
